# Dependabot will run on day 26 of each month at 03:02 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/src-admin'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '21 2 2 * *'
    open-pull-requests-limit: 15
    assignees:
      - 'GodHunter'
    versioning-strategy: 'increase'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      timezone: 'Europe/Berlin'
      cronjob: '21 2 2 * *'
    open-pull-requests-limit: 15
    assignees:
      - 'GodHunter'
